Tensor is a data structure, all the leading libraries like scikit learn, tensorflow, and pytorch are made on top of tensor.

### 0D Tensor/Scalar

In [11]:
import numpy as np

a = np.array(4)
print(f"the dimention of {a} array is {a.ndim}") # The output would be 0 i.e it's a scalar

the dimention of 4 array is 0


### 1D Tensor/Vectors

In [20]:
b = np.array([1,2,3,4])
print(f"The dimention of b = np.array([1,2]) i.e {b} is {b.ndim} which means this array is a vector but the dimention of vector is 2 dimentional vector because it has 2 elements")

The dimention of b = np.array([1,2]) i.e [1 2 3 4] is 1 which means this array is a vector but the dimention of vector is 2 dimentional vector because it has 2 elements


**1 dimentional array is vector and since we have 4 elements inside it, it's a 4 dimentional vector as well**

In [22]:
# similarly
c = np.array([1,2])
print(f"The dimention of c = np.array([1,2]) i.e {c} is {c.ndim} which means this array is a vector but the dimention of vector is 2 dimentional vector because it has 2 elements")

The dimention of c = np.array([1,2]) i.e [1 2] is 1 which means this array is a vector but the dimention of vector is 2 dimentional vector because it has 2 elements


### 2D Tensors/Matrices

In [24]:
d = np.array([[1,2,3,4],[2,3,5,6]])
print(f"the dimention of {d} array is {d.ndim} which is now an n dimentional array")

the dimention of [[1 2 3 4]
 [2 3 5 6]] array is 2 which is now an n dimentional array


In [26]:
e = np.array([[[1,2,3],
               [4,5,6]],
               [[3,4,5],
                [5,6,7]]])
print(f"the dimention of {e} array is {e.ndim} which is now an n dimentional array")

the dimention of [[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [5 6 7]]] array is 3 which is now an n dimentional array


## Rank Axes and Shapes

No. of axis = rank = no. of dimentions

### Shape of a tensor

In [30]:
print(f"We had the following metrices: {a}, {b}, {c}, {d}, and {e}. The shape of each of those metrices are as follows: {a.shape}, {b.shape}, {c.shape}, {d.shape}, and {e.shape}")

We had the following metrices: 4, [1 2 3 4], [1 2], [[1 2 3 4]
 [2 3 5 6]], and [[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [5 6 7]]]. The shape of each of those metrices are as follows: (), (4,), (2,), (2, 4), and (2, 2, 3)


As we can see "a" is a zero dimentional matrix because it has no shape, while "b",and "c" had just 1 dimention, "d" had 2 dimentions rows and columns while "e" has 3 dimentions i.e rows, columns and depth which is basically a cube in a way.

### Size of a tensor

Size of a tensor is defined as the total element within a tensor.

In [35]:
print(f"the size of a scalor tensor is always 1 no matter what is the total number of elements present in them, while the size of b is {b.size} so the number of elements in b tensor will be equal to it's size similary the size of e tensor is {e.size}")

the size of a scalor tensor is always 1 no matter what is the total number of elements present in them, while the size of b is 4 so the number of elements in b tensor will be equal to it's size similary the size of e tensor is 12
